# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CYow19SlkqBocNFis1jDIQw9cK8uA1nb

**EDA (Exploratory Data Analysis) using Sweetviz**
(From [Data Professor](https:/https://www.youtube.com/watch?v=UR_OK8vBpeY/))
"""

import pandas as pd
import sweetviz as sv
import IPython
from sklearn.model_selection import train_test_split

penguins = pd.read_csv('https://raw.githubusercontent.com/dataprofessor/data/master/penguins_cleaned.csv')

# X: independent variable
# y: dependent variable
X = penguins.drop('species', axis=1)
y = penguins['species']

"""Analyze the Dataset (penguins)"""

analyze_report = sv.analyze(penguins)
analyze_report.show_html('analyze_penguins_df.html', open_browser=False)

IPython.display.HTML('analyze_penguins_df.html')

"""Side-by-Side Comparation of Train vc Test Set
Data Split using 80/20 Split Ratio
"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

"""Comparison report"""

compare_report = sv.compare([X_train, 'Train'], [X_test, 'Test'])

compare_report.show_html('compare.html', open_browser=False)
IPython.display.HTML('compare.html')
